# Generated by Django 5.2 on 2025-05-09 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0001_initial'),
        ('members', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('reason', models.CharField(max_length=200, verbose_name='Lý do')),
                ('date_issued', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày phạt')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('borrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='circulation.borrowing', verbose_name='Giao dịch mượn')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='members.member', verbose_name='Độc giả')),
            ],
            options={
                'verbose_name': 'Phạt',
                'verbose_name_plural': 'Phạt',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã giao dịch')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Thanh toán'), ('REFUND', 'Hoàn tiền'), ('DEPOSIT', 'Đặt cọc')], max_length=10, verbose_name='Loại giao dịch')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày giao dịch')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.fine', verbose_name='Tiền phạt')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.member', verbose_name='Độc giả')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='staff.staff', verbose_name='Nhân viên xử lý')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'ordering': ['-date'],
            },
        ),
    ]
