# Generated by Django 5.2 on 2025-05-09 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('role', models.CharField(choices=[('LIBRARIAN', 'Thủ thư'), ('ADMIN', 'Quản trị'), ('ASSISTANT', 'Trợ lý')], default='ASSISTANT', max_length=20, verbose_name='Vai trò')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('hiring_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày vào làm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
