# Generated by Django 5.2 on 2025-05-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên tác giả')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Ngày mất')),
            ],
            options={
                'verbose_name': 'Tác giả',
                'verbose_name_plural': 'Tác giả',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thể loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà xuất bản')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Nhà xuất bản',
                'verbose_name_plural': 'Nhà xuất bản',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Tóm tắt')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Tổng số bản')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Số bản có sẵn')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngôn ngữ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Ảnh bìa')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số trang')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ManyToManyField(related_name='books', to='catalog.author', verbose_name='Tác giả')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.bookcategory', verbose_name='Thể loại')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.publisher', verbose_name='Nhà xuất bản')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'ordering': ['title'],
            },
        ),
    ]
