# Generated by Django 5.2 on 2025-05-09 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày mượn')),
                ('due_date', models.DateField(verbose_name='Ngày hẹn trả')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Ngày trả thực tế')),
                ('status', models.CharField(choices=[('BORROWING', 'Đang mượn'), ('RETURNED', 'Đã trả'), ('OVERDUE', 'Quá hạn'), ('LOST', 'Mất sách')], default='BORROWING', max_length=10, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='catalog.book', verbose_name='Tên sách')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='members.member', verbose_name='Người mượn')),
            ],
            options={
                'verbose_name': 'Mượn sách',
                'verbose_name_plural': 'Mượn sách',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đặt')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('FULFILLED', 'Đã thực hiện'), ('CANCELLED', 'Đã hủy'), ('EXPIRED', 'Hết hạn')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book', verbose_name='Tên sách')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='members.member', verbose_name='Người đặt trước')),
            ],
            options={
                'verbose_name': 'Đặt trước',
                'verbose_name_plural': 'Đặt trước',
                'ordering': ['-reservation_date'],
            },
        ),
    ]
