# Generated by Django 5.2 on 2025-05-09 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã thành viên')),
                ('membership_type', models.CharField(choices=[('STANDARD', 'Tiêu chuẩn'), ('PREMIUM', 'Cao cấp'), ('STUDENT', 'Sinh viên'), ('SENIOR', 'Người cao tuổi')], default='STANDARD', max_length=20, verbose_name='Loại thành viên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Ảnh đại diện')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Độc giả',
                'verbose_name_plural': 'Độc giả',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
